# Main composition file for Asterisk Application Container.
# Author: Arthur Cadore M. Barcella
# Github: arthurcadore
# Capacitação Redes - PV Intelbras

version: '3.8'
services:
  # Application container
  asteriskserver:
    container_name: asteriskserver
    hostname: dhcpserver
    restart: always
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    volumes:
      - "./config/extensions.conf:/etc/asterisk/extensions.conf"
      - "./config/sip.conf:/etc/asterisk/sip.conf"
      - "./config/voicemail.conf:/etc/asterisk/voicemail.conf"
    build:
      context: .
      dockerfile: ./app/Dockerfile